### ISSUE TITLE
opencv4.0中sift问题

### ISSUE THREAD

**Issue by WW-0** [JimmyHHua/opencv_tutorials#2]
想知道楼主怎么解决的sift等算法在一些opencv高版本中无法使用的问题

**Comment by NanQiL** [comment]
想知道楼主怎么解决的sift等算法在一些opencv高版本中无法使用的问题

**Comment by JimmyHHua** [comment]
你好，可以参考这个issue[https://github.com/skvark/opencv-python/issues/126](url)
