### ISSUE TITLE
Is there any assistance needed ?

### ISSUE THREAD

**Issue by Daniboy370** [JimmyHHua/opencv_tutorials#4]
Hi everyone,
I would love to contribute to this project, however I am not sure if maintainers are still active here ... 🤔
Would appreciate your answer.

**Comment by JimmyHHua** [comment]
Hi, welcome to contribute to it if you have any good idea and tutorials for opencv-python

**Comment by JimmyHHua** [comment]
> Hi everyone,
> I would love to contribute to this project, however I am not sure if maintainers are still active here ... 🤔
> Would appreciate your answer.

Hi, welcome to contribute to it if you have any good idea and tutorials for opencv-python

**Comment by JimmyHHua** [comment]
> 这是哪一本书的配套资源吗？有原书吗？想买一本一起看

没有书呢，是根据知识点罗列的学习路径
